### ISSUE TITLE
验证用户邮箱

### ISSUE THREAD

**Issue by flycash** [ecodeclub/webook#4]
正常来说，当用户使用了邮箱注册之后，其实这个时候我们并不是这个邮箱究竟是不是用户的邮箱。

比如说，我完全可以编造一个邮箱，然后注册。所以，一个关键点是要对邮箱进行验证。

验证分两种验证：
- 事前验证，也就是在注册之前，直接给邮箱发一个验证码，要求用户拿着验证码来注册
- 事后验证，注册成功之后，给邮箱发一个验证连接，提醒用户去验证。

那么你现在需要完成第一步：事后验证。也即是 SignUp 成功之后，你立刻发一封邮件出去。里面带上一个链接，这个链接就是验证的链接。

正常来说，验证了链接里面会带有 token。你可以考虑使用 JWT 来生成 token。这个 token 解析之后就能得到邮箱，那么你就知道是哪个邮箱验证了。而后在数据库里面标记一下这个邮箱是已经验证过了。

**Comment by shenxiang11** [comment]
有人🦐🐔👂用我的邮箱注册了，但是他验证不了；
然而等我想用邮箱注册的时候，我也注册不了，因为邮箱已经入库了，因为 mysql 上时 unique 的
